// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcjevsckdzernrygxzqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjamV2c2NrZHplcm5yeWd4enFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzgwMDYsImV4cCI6MjA2NDcxNDAwNn0.onawCD6MMJrWm5gn5lqFZnon9LHu8HXueGa1GxeZi7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);